/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.mailslurp.modelspackageVersion&#x3D;16.0.2

import java.util.UUID

case class EntityEventItemProjection(
  eventType: EntityEventItemProjectionEnums.EventType,
  inboxId: Option[UUID] = None,
  phoneId: Option[UUID] = None,
  id: UUID,
  severity: EntityEventItemProjectionEnums.Severity
)

object EntityEventItemProjectionEnums {

  type EventType = EventType.Value
  type Severity = Severity.Value
  object EventType extends Enumeration {
    val WEBHOOKEVENT = Value("WEBHOOK_EVENT")
    val INBOXFORWARDEREVENT = Value("INBOX_FORWARDER_EVENT")
    val INBOXREPLIEREVENT = Value("INBOX_REPLIER_EVENT")
    val INBOXRULESETEVENT = Value("INBOX_RULESET_EVENT")
    val ALIASEVENT = Value("ALIAS_EVENT")
  }

  object Severity extends Enumeration {
    val INFO = Value("INFO")
    val SUCCESS = Value("SUCCESS")
    val WARNING = Value("WARNING")
    val DANGER = Value("DANGER")
  }

}

