/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.mailslurp.modelspackageVersion&#x3D;17.4.0


  /**
   * Check a domain, IP address, or specific MX host against configured DNS blacklists
   */
case class CheckEmailBlacklistOptions(
  /* Domain to expand into A and MX host IPv4 addresses */
  domain: Option[String] = None,
  /* Specific IPv4 address to check directly */
  ipAddress: Option[String] = None,
  /* Specific MX host to resolve and check directly */
  mxHost: Option[String] = None,
  captchaToken: Option[String] = None
)


