/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.mailslurp.modelspackageVersion&#x3D;17.4.0


  /**
   * Simulation options for email deliverability tests
   */
case class DeliverabilitySimulationEmailOptions(
  /* Optional from override for each sent email */
  fromOverride: Option[String] = None,
  /* Optional email subject fallback used when template subject is omitted */
  subject: Option[String] = None,
  /* Optional email body template. Supports {{targetLabel}}, {{sendIndex}}, {{attempt}}. */
  bodyTemplate: Option[String] = None
)


