/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.mailslurp.modelspackageVersion&#x3D;17.0.0

import java.time.OffsetDateTime
import java.util.UUID

  /**
   * A compact representation of a full email. Used in list endpoints to keep response sizes low. Body and attachments are not included. To get all fields of the email use the `getEmail` method with the email projection's ID. See `EmailDto` for documentation on projection properties.
   */
case class EmailProjection(
  sender: Option[Sender] = None,
  recipients: Option[EmailRecipients] = None,
  attachments: Option[Seq[String]] = None,
  inboxId: UUID,
  createdAt: OffsetDateTime,
  to: Seq[String],
  cc: Option[Seq[String]] = None,
  bcc: Option[Seq[String]] = None,
  messageId: Option[String] = None,
  domainId: Option[UUID] = None,
  favourite: Option[Boolean] = None,
  plusAddress: Option[UUID] = None,
  sizeBytes: Option[Long] = None,
  inReplyTo: Option[String] = None,
  read: Boolean,
  bodyExcerpt: Option[String] = None,
  textExcerpt: Option[String] = None,
  bodyPartContentTypes: Option[Seq[String]] = None,
  bodyMD5Hash: Option[String] = None,
  teamAccess: Boolean,
  subject: Option[String] = None,
  id: UUID,
  threadId: Option[UUID] = None,
  from: String
)


