/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.mailslurp.apis

import com.mailslurp.modelspackageVersion&#x3D;17.3.0.AuditLogEventDto
import com.mailslurp.modelspackageVersion&#x3D;17.3.0.AuditLogPageDto
import com.mailslurp.modelspackageVersion&#x3D;17.3.0.AuditLogSearchOptions
import java.time.OffsetDateTime
import java.util.UUID
import com.mailslurp.client.core.JsonSupport._
import sttp.client._
import sttp.model.Method

object ApiAuditLogControllerApi {

def apply(baseUrl: String = "https://api.mailslurp.com") = new ApiAuditLogControllerApi(baseUrl)
}

class ApiAuditLogControllerApi(baseUrl: String) {

  /**
   * Expected answers:
   *   code 200 : AuditLogEventDto (OK)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param eventId 
   * @param since 
   * @param before 
   */
  def getAuditLogByEventId(apiKey: String)(eventId: String, since: Option[OffsetDateTime] = None, before: Option[OffsetDateTime] = None
): Request[Either[ResponseError[Exception], AuditLogEventDto], Nothing] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/audit-logs/${eventId}?since=${ since }&before=${ before }")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[AuditLogEventDto])

  /**
   * Expected answers:
   *   code 200 : AuditLogPageDto (OK)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param since 
   * @param before 
   * @param action 
   * @param userId 
   * @param actorUserId 
   * @param targetUserId 
   * @param resourceType 
   * @param resourceId 
   * @param outcome 
   * @param requestId 
   * @param ipAddress 
   * @param pageSize 
   * @param cursor 
   */
  def getAuditLogs(apiKey: String)(since: Option[OffsetDateTime] = None, before: Option[OffsetDateTime] = None, action: Option[String] = None, userId: Option[UUID] = None, actorUserId: Option[UUID] = None, targetUserId: Option[UUID] = None, resourceType: Option[String] = None, resourceId: Option[String] = None, outcome: Option[String] = None, requestId: Option[String] = None, ipAddress: Option[String] = None, pageSize: Option[Int] = None, cursor: Option[String] = None
): Request[Either[ResponseError[Exception], AuditLogPageDto], Nothing] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/audit-logs?since=${ since }&before=${ before }&action=${ action }&userId=${ userId }&actorUserId=${ actorUserId }&targetUserId=${ targetUserId }&resourceType=${ resourceType }&resourceId=${ resourceId }&outcome=${ outcome }&requestId=${ requestId }&ipAddress=${ ipAddress }&pageSize=${ pageSize }&cursor=${ cursor }")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[AuditLogPageDto])

  /**
   * Expected answers:
   *   code 200 : AuditLogPageDto (OK)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param auditLogSearchOptions 
   */
  def searchAuditLogs(apiKey: String)(auditLogSearchOptions: AuditLogSearchOptions
): Request[Either[ResponseError[Exception], AuditLogPageDto], Nothing] =
    basicRequest
      .method(Method.POST, uri"$baseUrl/audit-logs/search")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .body(auditLogSearchOptions)
      .response(asJson[AuditLogPageDto])

}
