/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.mailslurp.apis

import com.mailslurp.modelspackageVersion&#x3D;17.4.0.CreateDeliverabilitySimulationJobOptions
import com.mailslurp.modelspackageVersion&#x3D;17.4.0.CreateDeliverabilityTestOptions
import com.mailslurp.modelspackageVersion&#x3D;17.4.0.DeleteResult
import com.mailslurp.modelspackageVersion&#x3D;17.4.0.DeliverabilityAnalyticsSeriesDto
import com.mailslurp.modelspackageVersion&#x3D;17.4.0.DeliverabilityEntityResultPageDto
import com.mailslurp.modelspackageVersion&#x3D;17.4.0.DeliverabilityFailureHotspotsDto
import com.mailslurp.modelspackageVersion&#x3D;17.4.0.DeliverabilityPollStatusResultDto
import com.mailslurp.modelspackageVersion&#x3D;17.4.0.DeliverabilitySimulationJobDto
import com.mailslurp.modelspackageVersion&#x3D;17.4.0.DeliverabilitySimulationJobEventPageDto
import com.mailslurp.modelspackageVersion&#x3D;17.4.0.DeliverabilityTestDto
import com.mailslurp.modelspackageVersion&#x3D;17.4.0.DeliverabilityTestPageDto
import java.time.OffsetDateTime
import java.util.UUID
import com.mailslurp.modelspackageVersion&#x3D;17.4.0.UpdateDeliverabilityTestOptions
import com.mailslurp.client.core.JsonSupport._
import sttp.client._
import sttp.model.Method

object DeliverabilityTestControllerApi {

def apply(baseUrl: String = "https://api.mailslurp.com") = new DeliverabilityTestControllerApi(baseUrl)
}

class DeliverabilityTestControllerApi(baseUrl: String) {

  /**
   * Cancel a running or paused simulation job.
   * 
   * Expected answers:
   *   code 200 : DeliverabilitySimulationJobDto (OK)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param testId 
   * @param jobId 
   */
  def cancelDeliverabilitySimulationJob(apiKey: String)(testId: UUID, jobId: UUID
): Request[Either[ResponseError[Exception], DeliverabilitySimulationJobDto], Nothing] =
    basicRequest
      .method(Method.POST, uri"$baseUrl/test/deliverability/${testId}/simulation-jobs/${jobId}/cancel")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[DeliverabilitySimulationJobDto])

  /**
   * Create and start a simulation job for a running deliverability test. Only one active simulation job is allowed per user.
   * 
   * Expected answers:
   *   code 200 : DeliverabilitySimulationJobDto (OK)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param testId 
   * @param createDeliverabilitySimulationJobOptions 
   */
  def createDeliverabilitySimulationJob(apiKey: String)(testId: UUID, createDeliverabilitySimulationJobOptions: CreateDeliverabilitySimulationJobOptions
): Request[Either[ResponseError[Exception], DeliverabilitySimulationJobDto], Nothing] =
    basicRequest
      .method(Method.POST, uri"$baseUrl/test/deliverability/${testId}/simulation-jobs")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .body(createDeliverabilitySimulationJobOptions)
      .response(asJson[DeliverabilitySimulationJobDto])

  /**
   * Create a deliverability test for inboxes or phone numbers using ALL, PATTERN, or EXPLICIT selector scope.
   * 
   * Expected answers:
   *   code 200 : DeliverabilityTestDto (OK)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param createDeliverabilityTestOptions 
   */
  def createDeliverabilityTest(apiKey: String)(createDeliverabilityTestOptions: CreateDeliverabilityTestOptions
): Request[Either[ResponseError[Exception], DeliverabilityTestDto], Nothing] =
    basicRequest
      .method(Method.POST, uri"$baseUrl/test/deliverability")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .body(createDeliverabilityTestOptions)
      .response(asJson[DeliverabilityTestDto])

  /**
   * Delete test and all persisted entity-level results.
   * 
   * Expected answers:
   *   code 200 : DeleteResult (OK)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param testId 
   */
  def deleteDeliverabilityTest(apiKey: String)(testId: UUID
): Request[Either[ResponseError[Exception], DeleteResult], Nothing] =
    basicRequest
      .method(Method.DELETE, uri"$baseUrl/test/deliverability/${testId}")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[DeleteResult])

  /**
   * Create a fresh deliverability test using an existing test configuration, including selector scope, exclusions, and expectations.
   * 
   * Expected answers:
   *   code 200 : DeliverabilityTestDto (OK)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param testId 
   */
  def duplicateDeliverabilityTest(apiKey: String)(testId: UUID
): Request[Either[ResponseError[Exception], DeliverabilityTestDto], Nothing] =
    basicRequest
      .method(Method.POST, uri"$baseUrl/test/deliverability/${testId}/duplicate")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[DeliverabilityTestDto])

  /**
   * Export a PDF report for a terminal deliverability test (COMPLETE, FAILED, or STOPPED), including configuration, summary outcomes, and detailed entity-level results.
   * 
   * Expected answers:
   *   code 200 :  (OK)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param testId 
   */
  def exportDeliverabilityTestReport(apiKey: String)(testId: UUID
): Request[Either[ResponseError[Exception], Unit], Nothing] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/test/deliverability/${testId}/report/export")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[Unit])

  /**
   * Export per-entity deliverability results including expectation-level pass/fail counts. The latest status is evaluated with the same polling safeguards before export.
   * 
   * Expected answers:
   *   code 200 :  (OK)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param testId 
   * @param matched 
   */
  def exportDeliverabilityTestResults(apiKey: String)(testId: UUID, matched: Option[Boolean] = None
): Request[Either[ResponseError[Exception], Unit], Nothing] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/test/deliverability/${testId}/results/export?matched=${ matched }")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[Unit])

  /**
   * Compare deliverability runs over a time range with bucketed chart metrics and run-level rows for table views.
   * 
   * Expected answers:
   *   code 200 : DeliverabilityAnalyticsSeriesDto (OK)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param since 
   * @param before 
   * @param scope 
   * @param bucket 
   * @param runLimit 
   */
  def getDeliverabilityAnalyticsSeries(apiKey: String)(since: Option[OffsetDateTime] = None, before: Option[OffsetDateTime] = None, scope: Option[String] = None, bucket: Option[String] = None, runLimit: Option[Int] = None
): Request[Either[ResponseError[Exception], DeliverabilityAnalyticsSeriesDto], Nothing] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/test/deliverability/analytics/series?since=${ since }&before=${ before }&scope=${ scope }&bucket=${ bucket }&runLimit=${ runLimit }")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[DeliverabilityAnalyticsSeriesDto])

  /**
   * Find commonly failing entities and phone country/variant dimensions across deliverability runs in a time range.
   * 
   * Expected answers:
   *   code 200 : DeliverabilityFailureHotspotsDto (OK)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param since 
   * @param before 
   * @param scope 
   * @param limit 
   */
  def getDeliverabilityFailureHotspots(apiKey: String)(since: Option[OffsetDateTime] = None, before: Option[OffsetDateTime] = None, scope: Option[String] = None, limit: Option[Int] = None
): Request[Either[ResponseError[Exception], DeliverabilityFailureHotspotsDto], Nothing] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/test/deliverability/analytics/hotspots?since=${ since }&before=${ before }&scope=${ scope }&limit=${ limit }")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[DeliverabilityFailureHotspotsDto])

  /**
   * Get simulation job status and progress counters.
   * 
   * Expected answers:
   *   code 200 : DeliverabilitySimulationJobDto (OK)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param testId 
   * @param jobId 
   */
  def getDeliverabilitySimulationJob(apiKey: String)(testId: UUID, jobId: UUID
): Request[Either[ResponseError[Exception], DeliverabilitySimulationJobDto], Nothing] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/test/deliverability/${testId}/simulation-jobs/${jobId}")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[DeliverabilitySimulationJobDto])

  /**
   * Get paged simulation events including send successes and failures.
   * 
   * Expected answers:
   *   code 200 : DeliverabilitySimulationJobEventPageDto (OK)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param testId 
   * @param jobId 
   * @param page 
   * @param size 
   * @param sort 
   */
  def getDeliverabilitySimulationJobEvents(apiKey: String)(testId: UUID, jobId: UUID, page: Option[Int] = None, size: Option[Int] = None, sort: Option[String] = None
): Request[Either[ResponseError[Exception], DeliverabilitySimulationJobEventPageDto], Nothing] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/test/deliverability/${testId}/simulation-jobs/${jobId}/events?page=${ page }&size=${ size }&sort=${ sort }")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[DeliverabilitySimulationJobEventPageDto])

  /**
   * Get deliverability test configuration and latest progress counters.
   * 
   * Expected answers:
   *   code 200 : DeliverabilityTestDto (OK)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param testId 
   */
  def getDeliverabilityTest(apiKey: String)(testId: UUID
): Request[Either[ResponseError[Exception], DeliverabilityTestDto], Nothing] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/test/deliverability/${testId}")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[DeliverabilityTestDto])

  /**
   * Get paged per-entity expectation results with optional matched/unmatched filtering.
   * 
   * Expected answers:
   *   code 200 : DeliverabilityEntityResultPageDto (OK)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param testId 
   * @param matched 
   * @param page 
   * @param size 
   * @param sort 
   */
  def getDeliverabilityTestResults(apiKey: String)(testId: UUID, matched: Option[Boolean] = None, page: Option[Int] = None, size: Option[Int] = None, sort: Option[String] = None
): Request[Either[ResponseError[Exception], DeliverabilityEntityResultPageDto], Nothing] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/test/deliverability/${testId}/results?matched=${ matched }&page=${ page }&size=${ size }&sort=${ sort }")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[DeliverabilityEntityResultPageDto])

  /**
   * List deliverability tests for the authenticated account.
   * 
   * Expected answers:
   *   code 200 : DeliverabilityTestPageDto (OK)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param page Page index
   * @param size Page size
   * @param sort Sort direction
   */
  def getDeliverabilityTests(apiKey: String)(page: Option[Int] = None, size: Option[Int] = None, sort: Option[String] = None
): Request[Either[ResponseError[Exception], DeliverabilityTestPageDto], Nothing] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/test/deliverability?page=${ page }&size=${ size }&sort=${ sort }")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[DeliverabilityTestPageDto])

  /**
   * Get the most recent simulation job for a deliverability test.
   * 
   * Expected answers:
   *   code 200 : DeliverabilitySimulationJobDto (OK)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param testId 
   */
  def getLatestDeliverabilitySimulationJob(apiKey: String)(testId: UUID
): Request[Either[ResponseError[Exception], DeliverabilitySimulationJobDto], Nothing] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/test/deliverability/${testId}/simulation-jobs/latest")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[DeliverabilitySimulationJobDto])

  /**
   * Pause a running simulation job.
   * 
   * Expected answers:
   *   code 200 : DeliverabilitySimulationJobDto (OK)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param testId 
   * @param jobId 
   */
  def pauseDeliverabilitySimulationJob(apiKey: String)(testId: UUID, jobId: UUID
): Request[Either[ResponseError[Exception], DeliverabilitySimulationJobDto], Nothing] =
    basicRequest
      .method(Method.POST, uri"$baseUrl/test/deliverability/${testId}/simulation-jobs/${jobId}/pause")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[DeliverabilitySimulationJobDto])

  /**
   * Pause a RUNNING or SCHEDULED deliverability test.
   * 
   * Expected answers:
   *   code 200 : DeliverabilityTestDto (OK)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param testId 
   */
  def pauseDeliverabilityTest(apiKey: String)(testId: UUID
): Request[Either[ResponseError[Exception], DeliverabilityTestDto], Nothing] =
    basicRequest
      .method(Method.POST, uri"$baseUrl/test/deliverability/${testId}/pause")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[DeliverabilityTestDto])

  /**
   * Poll test progress. Evaluation is throttled with a 5-second cache window to protect backing data stores.
   * 
   * Expected answers:
   *   code 200 : DeliverabilityPollStatusResultDto (OK)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param testId 
   */
  def pollDeliverabilityTestStatus(apiKey: String)(testId: UUID
): Request[Either[ResponseError[Exception], DeliverabilityPollStatusResultDto], Nothing] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/test/deliverability/${testId}/status")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[DeliverabilityPollStatusResultDto])

  /**
   * Resume a paused simulation job.
   * 
   * Expected answers:
   *   code 200 : DeliverabilitySimulationJobDto (OK)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param testId 
   * @param jobId 
   */
  def resumeDeliverabilitySimulationJob(apiKey: String)(testId: UUID, jobId: UUID
): Request[Either[ResponseError[Exception], DeliverabilitySimulationJobDto], Nothing] =
    basicRequest
      .method(Method.POST, uri"$baseUrl/test/deliverability/${testId}/simulation-jobs/${jobId}/resume")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[DeliverabilitySimulationJobDto])

  /**
   * Start a CREATED test or resume a PAUSED/SCHEDULED test.
   * 
   * Expected answers:
   *   code 200 : DeliverabilityTestDto (OK)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param testId 
   */
  def startDeliverabilityTest(apiKey: String)(testId: UUID
): Request[Either[ResponseError[Exception], DeliverabilityTestDto], Nothing] =
    basicRequest
      .method(Method.POST, uri"$baseUrl/test/deliverability/${testId}/start")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[DeliverabilityTestDto])

  /**
   * Stop a deliverability test and mark it terminal.
   * 
   * Expected answers:
   *   code 200 : DeliverabilityTestDto (OK)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param testId 
   */
  def stopDeliverabilityTest(apiKey: String)(testId: UUID
): Request[Either[ResponseError[Exception], DeliverabilityTestDto], Nothing] =
    basicRequest
      .method(Method.POST, uri"$baseUrl/test/deliverability/${testId}/stop")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[DeliverabilityTestDto])

  /**
   * Update metadata, timeout, and expectations for a non-running non-terminal test.
   * 
   * Expected answers:
   *   code 200 : DeliverabilityTestDto (OK)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param testId 
   * @param updateDeliverabilityTestOptions 
   */
  def updateDeliverabilityTest(apiKey: String)(testId: UUID, updateDeliverabilityTestOptions: UpdateDeliverabilityTestOptions
): Request[Either[ResponseError[Exception], DeliverabilityTestDto], Nothing] =
    basicRequest
      .method(Method.PATCH, uri"$baseUrl/test/deliverability/${testId}")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .body(updateDeliverabilityTestOptions)
      .response(asJson[DeliverabilityTestDto])

}
