/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.mailslurp.apis

import com.mailslurp.modelspackageVersion&#x3D;17.5.0.ByteArray
import com.mailslurp.modelspackageVersion&#x3D;17.5.0.CancelDevicePreviewRunOptions
import com.mailslurp.modelspackageVersion&#x3D;17.5.0.CancelDevicePreviewRunResult
import com.mailslurp.modelspackageVersion&#x3D;17.5.0.CreateDevicePreviewFeedbackOptions
import com.mailslurp.modelspackageVersion&#x3D;17.5.0.CreateDevicePreviewOptions
import com.mailslurp.modelspackageVersion&#x3D;17.5.0.CreateDevicePreviewRunResult
import com.mailslurp.modelspackageVersion&#x3D;17.5.0.DeleteDevicePreviewRunResult
import com.mailslurp.modelspackageVersion&#x3D;17.5.0.DevicePreviewFeedbackDto
import com.mailslurp.modelspackageVersion&#x3D;17.5.0.DevicePreviewFeedbackListDto
import com.mailslurp.modelspackageVersion&#x3D;17.5.0.DevicePreviewProviderProgressDto
import com.mailslurp.modelspackageVersion&#x3D;17.5.0.DevicePreviewRunDto
import com.mailslurp.modelspackageVersion&#x3D;17.5.0.DevicePreviewRunResultsDto
import com.mailslurp.modelspackageVersion&#x3D;17.5.0.PageDevicePreviewRunProjection
import java.util.UUID
import com.mailslurp.modelspackageVersion&#x3D;17.5.0.UpdateDevicePreviewFeedbackOptions
import com.mailslurp.client.core.JsonSupport._
import sttp.client._
import sttp.model.Method

object DevicePreviewsControllerApi {

def apply(baseUrl: String = "https://api.mailslurp.com") = new DevicePreviewsControllerApi(baseUrl)
}

class DevicePreviewsControllerApi(baseUrl: String) {

  /**
   * Expected answers:
   *   code 200 : CancelDevicePreviewRunResult (OK)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param runId 
   * @param cancelDevicePreviewRunOptions 
   */
  def cancelDevicePreviewRun(apiKey: String)(runId: UUID, cancelDevicePreviewRunOptions: Option[CancelDevicePreviewRunOptions] = None
): Request[Either[ResponseError[Exception], CancelDevicePreviewRunResult], Nothing] =
    basicRequest
      .method(Method.POST, uri"$baseUrl/emails/device-previews/${runId}/cancel")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .body(cancelDevicePreviewRunOptions)
      .response(asJson[CancelDevicePreviewRunResult])

  /**
   * Expected answers:
   *   code 200 : DevicePreviewFeedbackDto (OK)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param createDevicePreviewFeedbackOptions 
   */
  def createDevicePreviewFeedback(apiKey: String)(createDevicePreviewFeedbackOptions: CreateDevicePreviewFeedbackOptions
): Request[Either[ResponseError[Exception], DevicePreviewFeedbackDto], Nothing] =
    basicRequest
      .method(Method.POST, uri"$baseUrl/emails/device-previews/feedback")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .body(createDevicePreviewFeedbackOptions)
      .response(asJson[DevicePreviewFeedbackDto])

  /**
   * Expected answers:
   *   code 200 : CreateDevicePreviewRunResult (OK)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param emailId 
   * @param createDevicePreviewOptions 
   */
  def createDevicePreviewRun(apiKey: String)(emailId: UUID, createDevicePreviewOptions: Option[CreateDevicePreviewOptions] = None
): Request[Either[ResponseError[Exception], CreateDevicePreviewRunResult], Nothing] =
    basicRequest
      .method(Method.POST, uri"$baseUrl/emails/${emailId}/device-previews")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .body(createDevicePreviewOptions)
      .response(asJson[CreateDevicePreviewRunResult])

  /**
   * Expected answers:
   *   code 200 : DeleteDevicePreviewRunResult (OK)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param runId 
   */
  def deleteDevicePreviewRun(apiKey: String)(runId: UUID
): Request[Either[ResponseError[Exception], DeleteDevicePreviewRunResult], Nothing] =
    basicRequest
      .method(Method.DELETE, uri"$baseUrl/emails/device-previews/${runId}")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[DeleteDevicePreviewRunResult])

  /**
   * Expected answers:
   *   code 200 : CreateDevicePreviewRunResult (OK)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param emailId 
   * @param createDevicePreviewOptions 
   */
  def ensureDevicePreviewRun(apiKey: String)(emailId: UUID, createDevicePreviewOptions: Option[CreateDevicePreviewOptions] = None
): Request[Either[ResponseError[Exception], CreateDevicePreviewRunResult], Nothing] =
    basicRequest
      .method(Method.PUT, uri"$baseUrl/emails/${emailId}/device-previews/latest")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .body(createDevicePreviewOptions)
      .response(asJson[CreateDevicePreviewRunResult])

  /**
   * Expected answers:
   *   code 200 : DevicePreviewFeedbackDto (OK)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param feedbackId 
   */
  def getDevicePreviewFeedback(apiKey: String)(feedbackId: UUID
): Request[Either[ResponseError[Exception], DevicePreviewFeedbackDto], Nothing] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/emails/device-previews/feedback/${feedbackId}")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[DevicePreviewFeedbackDto])

  /**
   * Expected answers:
   *   code 200 : DevicePreviewFeedbackListDto (OK)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param page 
   * @param size 
   * @param source 
   * @param runId 
   * @param status 
   * @param provider 
   * @param category 
   * @param search 
   */
  def getDevicePreviewFeedbackItems(apiKey: String)(page: Option[Int] = None, size: Option[Int] = None, source: Option[String] = None, runId: Option[UUID] = None, status: Option[String] = None, provider: Option[String] = None, category: Option[String] = None, search: Option[String] = None
): Request[Either[ResponseError[Exception], DevicePreviewFeedbackListDto], Nothing] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/emails/device-previews/feedback?page=${ page }&size=${ size }&source=${ source }&runId=${ runId }&status=${ status }&provider=${ provider }&category=${ category }&search=${ search }")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[DevicePreviewFeedbackListDto])

  /**
   * Expected answers:
   *   code 200 : DevicePreviewRunDto (OK)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param runId 
   */
  def getDevicePreviewRun(apiKey: String)(runId: UUID
): Request[Either[ResponseError[Exception], DevicePreviewRunDto], Nothing] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/emails/device-previews/${runId}")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[DevicePreviewRunDto])

  /**
   * Expected answers:
   *   code 200 : DevicePreviewProviderProgressDto (OK)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param runId 
   * @param provider 
   */
  def getDevicePreviewRunProviderProgress(apiKey: String)(runId: UUID, provider: String
): Request[Either[ResponseError[Exception], DevicePreviewProviderProgressDto], Nothing] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/emails/device-previews/${runId}/providers/${provider}")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[DevicePreviewProviderProgressDto])

  /**
   * Expected answers:
   *   code 200 : DevicePreviewRunResultsDto (OK)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param runId 
   */
  def getDevicePreviewRunResults(apiKey: String)(runId: UUID
): Request[Either[ResponseError[Exception], DevicePreviewRunResultsDto], Nothing] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/emails/device-previews/${runId}/results")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[DevicePreviewRunResultsDto])

  /**
   * Expected answers:
   *   code 200 : ByteArray (OK)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param runId 
   * @param screenshotId 
   */
  def getDevicePreviewRunScreenshot(apiKey: String)(runId: UUID, screenshotId: UUID
): Request[Either[ResponseError[Exception], ByteArray], Nothing] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/emails/device-previews/${runId}/screenshots/${screenshotId}/image")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[ByteArray])

  /**
   * Expected answers:
   *   code 200 : Seq[DevicePreviewRunDto] (OK)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param emailId 
   * @param limit 
   */
  def getDevicePreviewRuns(apiKey: String)(emailId: UUID, limit: Option[Int] = None
): Request[Either[ResponseError[Exception], Seq[DevicePreviewRunDto]], Nothing] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/emails/${emailId}/device-previews?limit=${ limit }")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[Seq[DevicePreviewRunDto]])

  /**
   * Expected answers:
   *   code 200 : Seq[DevicePreviewRunDto] (OK)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param limit 
   */
  def getDevicePreviewRunsForAccount(apiKey: String)(limit: Option[Int] = None
): Request[Either[ResponseError[Exception], Seq[DevicePreviewRunDto]], Nothing] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/emails/device-previews?limit=${ limit }")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[Seq[DevicePreviewRunDto]])

  /**
   * Expected answers:
   *   code 200 : PageDevicePreviewRunProjection (OK)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param emailId 
   * @param page Optional page index in list pagination
   * @param size Optional page size for paginated result list.
   * @param sort Optional createdAt sort direction ASC or DESC
   */
  def getDevicePreviewRunsOffsetPaginated(apiKey: String)(emailId: UUID, page: Option[Int] = None, size: Option[Int] = None, sort: Option[String] = None
): Request[Either[ResponseError[Exception], PageDevicePreviewRunProjection], Nothing] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/emails/${emailId}/device-previews/offset-paginated?page=${ page }&size=${ size }&sort=${ sort }")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[PageDevicePreviewRunProjection])

  /**
   * Expected answers:
   *   code 200 : DevicePreviewFeedbackDto (OK)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param feedbackId 
   * @param updateDevicePreviewFeedbackOptions 
   */
  def updateDevicePreviewFeedback(apiKey: String)(feedbackId: UUID, updateDevicePreviewFeedbackOptions: UpdateDevicePreviewFeedbackOptions
): Request[Either[ResponseError[Exception], DevicePreviewFeedbackDto], Nothing] =
    basicRequest
      .method(Method.PUT, uri"$baseUrl/emails/device-previews/feedback/${feedbackId}")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .body(updateDevicePreviewFeedbackOptions)
      .response(asJson[DevicePreviewFeedbackDto])

}
