/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.mailslurp.apis

import com.mailslurp.modelspackageVersion&#x3D;14.0.2.AbstractWebhookPayload
import com.mailslurp.modelspackageVersion&#x3D;14.0.2.CreateWebhookOptions
import com.mailslurp.modelspackageVersion&#x3D;14.0.2.JSONSchemaDto
import java.time.OffsetDateTime
import com.mailslurp.modelspackageVersion&#x3D;14.0.2.PageWebhookProjection
import com.mailslurp.modelspackageVersion&#x3D;14.0.2.PageWebhookResult
import java.util.UUID
import com.mailslurp.modelspackageVersion&#x3D;14.0.2.UnseenErrorCountDto
import com.mailslurp.modelspackageVersion&#x3D;14.0.2.WebhookDto
import com.mailslurp.modelspackageVersion&#x3D;14.0.2.WebhookEmailOpenedPayload
import com.mailslurp.modelspackageVersion&#x3D;14.0.2.WebhookEmailReadPayload
import com.mailslurp.modelspackageVersion&#x3D;14.0.2.WebhookNewAttachmentPayload
import com.mailslurp.modelspackageVersion&#x3D;14.0.2.WebhookNewContactPayload
import com.mailslurp.modelspackageVersion&#x3D;14.0.2.WebhookNewEmailPayload
import com.mailslurp.modelspackageVersion&#x3D;14.0.2.WebhookRedriveResult
import com.mailslurp.modelspackageVersion&#x3D;14.0.2.WebhookResultDto
import com.mailslurp.modelspackageVersion&#x3D;14.0.2.WebhookTestResult
import com.mailslurp.client.core.JsonSupport._
import sttp.client._
import sttp.model.Method

object WebhookControllerApi {

def apply(baseUrl: String = "https://api.mailslurp.com") = new WebhookControllerApi(baseUrl)
}

class WebhookControllerApi(baseUrl: String) {

  /**
   * Get notified whenever an inbox receives an email via a WebHook URL. An emailID will be posted to this URL every time an email is received for this inbox. The URL must be publicly reachable by the MailSlurp server. You can provide basicAuth values if you wish to secure this endpoint.
   * 
   * Expected answers:
   *   code 201 : WebhookDto (Created)
   *   code 401 :  (Unauthorized)
   *   code 403 :  (Forbidden)
   *   code 404 :  (Not Found)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param inboxId inboxId
   * @param webhookOptions webhookOptions
   */
  def createWebhook(apiKey: String)(inboxId: UUID, webhookOptions: CreateWebhookOptions
): Request[Either[ResponseError[Exception], WebhookDto], Nothing] =
    basicRequest
      .method(Method.POST, uri"$baseUrl/inboxes/${inboxId}/webhooks")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .body(webhookOptions)
      .response(asJson[WebhookDto])

  /**
   * Expected answers:
   *   code 204 :  (No Content)
   *   code 401 :  (Unauthorized)
   *   code 403 :  (Forbidden)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   */
  def deleteAllWebhooks(apiKey: String)(
): Request[Either[ResponseError[Exception], Unit], Nothing] =
    basicRequest
      .method(Method.DELETE, uri"$baseUrl/webhooks")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[Unit])

  /**
   * Expected answers:
   *   code 204 :  (No Content)
   *   code 401 :  (Unauthorized)
   *   code 403 :  (Forbidden)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param inboxId inboxId
   * @param webhookId webhookId
   */
  def deleteWebhook(apiKey: String)(inboxId: UUID, webhookId: UUID
): Request[Either[ResponseError[Exception], Unit], Nothing] =
    basicRequest
      .method(Method.DELETE, uri"$baseUrl/inboxes/${inboxId}/webhooks/${webhookId}")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[Unit])

  /**
   * Expected answers:
   *   code 200 : PageWebhookResult (OK)
   *   code 401 :  (Unauthorized)
   *   code 403 :  (Forbidden)
   *   code 404 :  (Not Found)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param before Filter by created at before the given timestamp
   * @param page Optional page index in list pagination
   * @param searchFilter Optional search filter
   * @param since Filter by created at after the given timestamp
   * @param size Optional page size in list pagination
   * @param sort Optional createdAt sort direction ASC or DESC
   * @param unseenOnly Filter for unseen exceptions only
   */
  def getAllWebhookResults(apiKey: String)(before: Option[OffsetDateTime] = None, page: Option[Int] = None, searchFilter: Option[String] = None, since: Option[OffsetDateTime] = None, size: Option[Int] = None, sort: Option[String] = None, unseenOnly: Option[Boolean] = None
): Request[Either[ResponseError[Exception], PageWebhookResult], Nothing] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/webhooks/results?before=${ before }&page=${ page }&searchFilter=${ searchFilter }&since=${ since }&size=${ size }&sort=${ sort }&unseenOnly=${ unseenOnly }")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[PageWebhookResult])

  /**
   * List webhooks in paginated form. Allows for page index, page size, and sort direction.
   * 
   * Expected answers:
   *   code 200 : PageWebhookProjection (OK)
   *   code 401 :  (Unauthorized)
   *   code 403 :  (Forbidden)
   *   code 404 :  (Not Found)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param before Filter by created at before the given timestamp
   * @param page Optional page index in list pagination
   * @param searchFilter Optional search filter
   * @param since Filter by created at after the given timestamp
   * @param size Optional page size for paginated result list.
   * @param sort Optional createdAt sort direction ASC or DESC
   */
  def getAllWebhooks(apiKey: String)(before: Option[OffsetDateTime] = None, page: Option[Int] = None, searchFilter: Option[String] = None, since: Option[OffsetDateTime] = None, size: Option[Int] = None, sort: Option[String] = None
): Request[Either[ResponseError[Exception], PageWebhookProjection], Nothing] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/webhooks/paginated?before=${ before }&page=${ page }&searchFilter=${ searchFilter }&since=${ since }&size=${ size }&sort=${ sort }")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[PageWebhookProjection])

  /**
   * Expected answers:
   *   code 200 : PageWebhookProjection (OK)
   *   code 401 :  (Unauthorized)
   *   code 403 :  (Forbidden)
   *   code 404 :  (Not Found)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param inboxId inboxId
   * @param before Filter by created at before the given timestamp
   * @param page Optional page index in list pagination
   * @param searchFilter Optional search filter
   * @param since Filter by created at after the given timestamp
   * @param size Optional page size in list pagination
   * @param sort Optional createdAt sort direction ASC or DESC
   */
  def getInboxWebhooksPaginated(apiKey: String)(inboxId: UUID, before: Option[OffsetDateTime] = None, page: Option[Int] = None, searchFilter: Option[String] = None, since: Option[OffsetDateTime] = None, size: Option[Int] = None, sort: Option[String] = None
): Request[Either[ResponseError[Exception], PageWebhookProjection], Nothing] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/inboxes/${inboxId}/webhooks/paginated?before=${ before }&page=${ page }&searchFilter=${ searchFilter }&since=${ since }&size=${ size }&sort=${ sort }")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[PageWebhookProjection])

  /**
   * Expected answers:
   *   code 201 : JSONSchemaDto (Created)
   *   code 401 :  (Unauthorized)
   *   code 403 :  (Forbidden)
   *   code 404 :  (Not Found)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param webhookId webhookId
   */
  def getJsonSchemaForWebhookPayload(apiKey: String)(webhookId: UUID
): Request[Either[ResponseError[Exception], JSONSchemaDto], Nothing] =
    basicRequest
      .method(Method.POST, uri"$baseUrl/webhooks/${webhookId}/schema")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[JSONSchemaDto])

  /**
   * Expected answers:
   *   code 200 : AbstractWebhookPayload (OK)
   *   code 401 :  (Unauthorized)
   *   code 403 :  (Forbidden)
   *   code 404 :  (Not Found)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param eventName eventName
   */
  def getTestWebhookPayload(apiKey: String)(eventName: Option[String] = None
): Request[Either[ResponseError[Exception], AbstractWebhookPayload], Nothing] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/webhooks/test?eventName=${ eventName }")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[AbstractWebhookPayload])

  /**
   * Expected answers:
   *   code 200 : WebhookEmailOpenedPayload (OK)
   *   code 401 :  (Unauthorized)
   *   code 403 :  (Forbidden)
   *   code 404 :  (Not Found)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   */
  def getTestWebhookPayloadEmailOpened(apiKey: String)(
): Request[Either[ResponseError[Exception], WebhookEmailOpenedPayload], Nothing] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/webhooks/test/email-opened-payload")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[WebhookEmailOpenedPayload])

  /**
   * Expected answers:
   *   code 200 : WebhookEmailReadPayload (OK)
   *   code 401 :  (Unauthorized)
   *   code 403 :  (Forbidden)
   *   code 404 :  (Not Found)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   */
  def getTestWebhookPayloadEmailRead(apiKey: String)(
): Request[Either[ResponseError[Exception], WebhookEmailReadPayload], Nothing] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/webhooks/test/email-read-payload")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[WebhookEmailReadPayload])

  /**
   * Expected answers:
   *   code 201 : AbstractWebhookPayload (Created)
   *   code 401 :  (Unauthorized)
   *   code 403 :  (Forbidden)
   *   code 404 :  (Not Found)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param webhookId webhookId
   */
  def getTestWebhookPayloadForWebhook(apiKey: String)(webhookId: UUID
): Request[Either[ResponseError[Exception], AbstractWebhookPayload], Nothing] =
    basicRequest
      .method(Method.POST, uri"$baseUrl/webhooks/${webhookId}/example")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[AbstractWebhookPayload])

  /**
   * Expected answers:
   *   code 200 : WebhookNewAttachmentPayload (OK)
   *   code 401 :  (Unauthorized)
   *   code 403 :  (Forbidden)
   *   code 404 :  (Not Found)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   */
  def getTestWebhookPayloadNewAttachment(apiKey: String)(
): Request[Either[ResponseError[Exception], WebhookNewAttachmentPayload], Nothing] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/webhooks/test/new-attachment-payload")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[WebhookNewAttachmentPayload])

  /**
   * Expected answers:
   *   code 200 : WebhookNewContactPayload (OK)
   *   code 401 :  (Unauthorized)
   *   code 403 :  (Forbidden)
   *   code 404 :  (Not Found)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   */
  def getTestWebhookPayloadNewContact(apiKey: String)(
): Request[Either[ResponseError[Exception], WebhookNewContactPayload], Nothing] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/webhooks/test/new-contact-payload")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[WebhookNewContactPayload])

  /**
   * Expected answers:
   *   code 200 : WebhookNewEmailPayload (OK)
   *   code 401 :  (Unauthorized)
   *   code 403 :  (Forbidden)
   *   code 404 :  (Not Found)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   */
  def getTestWebhookPayloadNewEmail(apiKey: String)(
): Request[Either[ResponseError[Exception], WebhookNewEmailPayload], Nothing] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/webhooks/test/new-email-payload")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[WebhookNewEmailPayload])

  /**
   * Expected answers:
   *   code 200 : WebhookDto (OK)
   *   code 401 :  (Unauthorized)
   *   code 403 :  (Forbidden)
   *   code 404 :  (Not Found)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param webhookId webhookId
   */
  def getWebhook(apiKey: String)(webhookId: UUID
): Request[Either[ResponseError[Exception], WebhookDto], Nothing] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/webhooks/${webhookId}")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[WebhookDto])

  /**
   * Expected answers:
   *   code 200 : WebhookResultDto (OK)
   *   code 401 :  (Unauthorized)
   *   code 403 :  (Forbidden)
   *   code 404 :  (Not Found)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param webhookResultId Webhook Result ID
   */
  def getWebhookResult(apiKey: String)(webhookResultId: UUID
): Request[Either[ResponseError[Exception], WebhookResultDto], Nothing] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/webhooks/results/${webhookResultId}")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[WebhookResultDto])

  /**
   * Expected answers:
   *   code 200 : PageWebhookResult (OK)
   *   code 401 :  (Unauthorized)
   *   code 403 :  (Forbidden)
   *   code 404 :  (Not Found)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param webhookId ID of webhook to get results for
   * @param before Filter by created at before the given timestamp
   * @param page Optional page index in list pagination
   * @param searchFilter Optional search filter
   * @param since Filter by created at after the given timestamp
   * @param size Optional page size in list pagination
   * @param sort Optional createdAt sort direction ASC or DESC
   * @param unseenOnly Filter for unseen exceptions only
   */
  def getWebhookResults(apiKey: String)(webhookId: UUID, before: Option[OffsetDateTime] = None, page: Option[Int] = None, searchFilter: Option[String] = None, since: Option[OffsetDateTime] = None, size: Option[Int] = None, sort: Option[String] = None, unseenOnly: Option[Boolean] = None
): Request[Either[ResponseError[Exception], PageWebhookResult], Nothing] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/webhooks/${webhookId}/results?before=${ before }&page=${ page }&searchFilter=${ searchFilter }&since=${ since }&size=${ size }&sort=${ sort }&unseenOnly=${ unseenOnly }")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[PageWebhookResult])

  /**
   * Expected answers:
   *   code 200 : UnseenErrorCountDto (OK)
   *   code 401 :  (Unauthorized)
   *   code 403 :  (Forbidden)
   *   code 404 :  (Not Found)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param inboxId inboxId
   */
  def getWebhookResultsUnseenErrorCount(apiKey: String)(inboxId: UUID
): Request[Either[ResponseError[Exception], UnseenErrorCountDto], Nothing] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/webhooks/results/unseen-count")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[UnseenErrorCountDto])

  /**
   * Expected answers:
   *   code 200 : Seq[WebhookDto] (OK)
   *   code 401 :  (Unauthorized)
   *   code 403 :  (Forbidden)
   *   code 404 :  (Not Found)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param inboxId inboxId
   */
  def getWebhooks(apiKey: String)(inboxId: UUID
): Request[Either[ResponseError[Exception], Seq[WebhookDto]], Nothing] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/inboxes/${inboxId}/webhooks")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[Seq[WebhookDto]])

  /**
   * Allows you to resend a webhook payload that was already sent. Webhooks that fail are retried automatically for 24 hours and then put in a dead letter queue. You can retry results manually using this method.
   * 
   * Expected answers:
   *   code 200 : WebhookRedriveResult (OK)
   *   code 201 :  (Created)
   *   code 401 :  (Unauthorized)
   *   code 403 :  (Forbidden)
   *   code 404 :  (Not Found)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param webhookResultId Webhook Result ID
   */
  def redriveWebhookResult(apiKey: String)(webhookResultId: UUID
): Request[Either[ResponseError[Exception], WebhookRedriveResult], Nothing] =
    basicRequest
      .method(Method.POST, uri"$baseUrl/webhooks/results/${webhookResultId}/redrive")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[WebhookRedriveResult])

  /**
   * Expected answers:
   *   code 201 : WebhookTestResult (Created)
   *   code 401 :  (Unauthorized)
   *   code 403 :  (Forbidden)
   *   code 404 :  (Not Found)
   * 
   * Available security schemes:
   *   API_KEY (apiKey)
   * 
   * @param webhookId webhookId
   */
  def sendTestData(apiKey: String)(webhookId: UUID
): Request[Either[ResponseError[Exception], WebhookTestResult], Nothing] =
    basicRequest
      .method(Method.POST, uri"$baseUrl/webhooks/${webhookId}/test")
      .contentType("application/json")
      .header("x-api-key", apiKey)
      .response(asJson[WebhookTestResult])

}
