/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.mailslurp.modelspackageVersion&#x3D;17.5.0


  /**
   * Public blacklist lookup results for a domain or IP address
   */
case class CheckEmailBlacklistResults(
  domain: Option[String] = None,
  requestedIpAddress: Option[String] = None,
  requestedMxHost: Option[String] = None,
  status: CheckEmailBlacklistResultsEnums.Status,
  listed: Boolean,
  checkedIpAddresses: Seq[EmailBlacklistIpResult],
  checkedZoneCount: Int,
  totalListings: Int,
  warnings: Seq[String],
  errors: Seq[String]
)

object CheckEmailBlacklistResultsEnums {

  type Status = Status.Value
  object Status extends Enumeration {
    val HEALTHY = Value("HEALTHY")
    val DEGRADED = Value("DEGRADED")
    val CRITICAL = Value("CRITICAL")
    val FAILED = Value("FAILED")
  }

}

