/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.mailslurp.modelspackageVersion&#x3D;17.5.0


case class DomainRegionInformation(
  domainName: String,
  verified: Boolean,
  /* Type of domain. Dictates type of inbox that can be created with domain. HTTP means inboxes are processed using SES while SMTP inboxes use a custom SMTP mail server. SMTP does not support sending so use HTTP for sending emails. */
  domainType: DomainRegionInformationEnums.DomainType,
  accountRegion: Option[DomainRegionInformationEnums.AccountRegion] = None,
  creationEnabled: Boolean,
  sendingEnabled: Boolean,
  active: Boolean
)

object DomainRegionInformationEnums {

  type DomainType = DomainType.Value
  type AccountRegion = AccountRegion.Value
  object DomainType extends Enumeration {
    val HTTPINBOX = Value("HTTP_INBOX")
    val SMTPDOMAIN = Value("SMTP_DOMAIN")
  }

  object AccountRegion extends Enumeration {
    val USWEST2ACCOUNTSTAGING = Value("US_WEST_2_ACCOUNT_STAGING")
    val USEAST1ACCOUNTSTAGING = Value("US_EAST_1_ACCOUNT_STAGING")
    val EUWEST1ACCOUNTSTAGING = Value("EU_WEST_1_ACCOUNT_STAGING")
    val USWEST2ACCOUNTSES1 = Value("US_WEST_2_ACCOUNT_SES_1")
    val EUWEST1ACCOUNTSES1 = Value("EU_WEST_1_ACCOUNT_SES_1")
    val USWEST2ACCOUNTSES2 = Value("US_WEST_2_ACCOUNT_SES_2")
    val EUWEST1ACCOUNTSES2 = Value("EU_WEST_1_ACCOUNT_SES_2")
    val USWEST2ACCOUNTBYTEWISE = Value("US_WEST_2_ACCOUNT_BYTEWISE")
    val EUWEST1ACCOUNTBYTEWISE = Value("EU_WEST_1_ACCOUNT_BYTEWISE")
    val USWEST2 = Value("US_WEST_2")
    val EUWEST1 = Value("EU_WEST_1")
    val USEAST1 = Value("US_EAST_1")
  }

}

