/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.mailslurp.modelspackageVersion&#x3D;17.5.0


  /**
   * Request options for running email intelligence checks on one or more inputs.
   */
case class EmailIntelligenceOptions(
  /* Email addresses or domains to score. */
  targets: Seq[String],
  /* Zero-based page index for processing a subset of the target list. */
  page: Option[Int] = None,
  /* Page size for processing a subset of the target list. */
  size: Option[Int] = None,
  /* Ignore cached intelligence values and force recomputation. */
  ignoreCache: Option[Boolean] = None,
  /* Also run mailbox safety verification using the existing verification client for email inputs. */
  includeEmailValidation: Option[Boolean] = None,
  tests: Option[EmailIntelligenceTestsOptions] = None
)


