/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.mailslurp.modelspackageVersion&#x3D;17.5.0


  /**
   * Options for importing a raw RFC822/MIME email into a specific inbox. V1 supports MIME-family formats such as `.eml`, `message/rfc822`, and raw MIME bytes. Outlook `.msg`, `mbox`, and `maildir` are not supported in V1.
   */
case class ImportEmailOptions(
  /* Base64 encoded RFC822/MIME email contents. This should be the full raw email including headers and body, such as the bytes from an `.eml` file. */
  rawEmailBase64: String,
  /* Optional external identifier for the imported email source. Useful for correlating imports back to another system. */
  externalId: Option[String] = None,
  /* When true the normal inbound receive pipeline runs after persistence, including automations, webhooks, transformers, forwarders, repliers, and related fanout. When false the email is stored only. */
  runPipeline: Option[Boolean] = None,
  /* When true MailSlurp rewrites the MIME `Message-ID` header before storing and parsing the email so imported messages do not collide with existing message identities. */
  overrideMessageId: Option[Boolean] = None
)


