/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.mailslurp.modelspackageVersion&#x3D;17.5.0

import java.time.OffsetDateTime
import java.util.UUID

  /**
   * Released phone number projection
   */
case class PhoneNumberReleaseProjection(
  name: Option[String] = None,
  id: UUID,
  userId: UUID,
  phoneCountry: PhoneNumberReleaseProjectionEnums.PhoneCountry,
  createdAt: OffsetDateTime,
  phoneNumber: Option[String] = None,
  subscriptionSchedule: Option[PhoneNumberReleaseProjectionEnums.SubscriptionSchedule] = None,
  planCurrency: Option[PhoneNumberReleaseProjectionEnums.PlanCurrency] = None
)

object PhoneNumberReleaseProjectionEnums {

  type PhoneCountry = PhoneCountry.Value
  type SubscriptionSchedule = SubscriptionSchedule.Value
  type PlanCurrency = PlanCurrency.Value
  object PhoneCountry extends Enumeration {
    val US = Value("US")
    val GB = Value("GB")
    val AU = Value("AU")
    val CA = Value("CA")
    val EE = Value("EE")
    val HK = Value("HK")
    val PL = Value("PL")
    val PT = Value("PT")
    val NL = Value("NL")
    val IL = Value("IL")
    val FI = Value("FI")
    val SE = Value("SE")
  }

  object SubscriptionSchedule extends Enumeration {
    val MONTHLY = Value("MONTHLY")
    val YEARLY = Value("YEARLY")
  }

  object PlanCurrency extends Enumeration {
    val EUR = Value("EUR")
    val USD = Value("USD")
    val JPY = Value("JPY")
    val GBP = Value("GBP")
    val AUD = Value("AUD")
    val CAD = Value("CAD")
    val CHF = Value("CHF")
    val CNY = Value("CNY")
    val INR = Value("INR")
    val NZD = Value("NZD")
  }

}

