/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.mailslurp.modelspackageVersion&#x3D;17.2.0


  /**
   * Options for matching when an AI transform mapping should trigger. Each match option object contains a `field`, `should` and `value` property. Together they form logical conditions such as `SUBJECT` should `CONTAIN` value.
   */
case class AIMappingMatchOption(
  /* Fields of an email, sms, or attachment object that can be used to filter results */
  field: AIMappingMatchOptionEnums.Field,
  /* How the value of the field specified should be compared to the value given in the match options. */
  should: AIMappingMatchOptionEnums.Should,
  /* The value you wish to compare with the value of the field specified using the `should` value passed. For example `BODY` should `CONTAIN` a value passed. When should value is `MATCH` pass a regex */
  value: String
)

object AIMappingMatchOptionEnums {

  type Field = Field.Value
  type Should = Should.Value
  object Field extends Enumeration {
    val SUBJECT = Value("SUBJECT")
    val TO = Value("TO")
    val BCC = Value("BCC")
    val CC = Value("CC")
    val FROM = Value("FROM")
    val HEADERS = Value("HEADERS")
    val FILENAME = Value("FILENAME")
    val SMS = Value("SMS")
  }

  object Should extends Enumeration {
    val `MATCH` = Value("MATCH")
    val CONTAIN = Value("CONTAIN")
    val EQUAL = Value("EQUAL")
  }

}

