/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.mailslurp.modelspackageVersion&#x3D;17.2.0

import java.util.UUID

  /**
   * How entities are selected for a deliverability test
   */
case class DeliverabilitySelectorOptions(
  /* Selection mode */
  `type`: DeliverabilitySelectorOptionsEnums.`Type`,
  /* Wildcard pattern for PATTERN selection. Supports '*' and '?' wildcards. If no wildcard is present the value is treated as a case-insensitive contains match. */
  pattern: Option[String] = None,
  /* Optional phone-country filter for PHONE scope selection (e.g. ALL phones in US). Must be null for INBOX scope. */
  phoneCountry: Option[DeliverabilitySelectorOptionsEnums.PhoneCountry] = None,
  /* Explicit entity IDs for EXPLICIT selection */
  entityIds: Option[Seq[UUID]] = None,
  /* Optional entity IDs to exclude from the resolved selection (applies after ALL/PATTERN/EXPLICIT selection). */
  excludeEntityIds: Option[Seq[UUID]] = None
)

object DeliverabilitySelectorOptionsEnums {

  type `Type` = `Type`.Value
  type PhoneCountry = PhoneCountry.Value
  object `Type` extends Enumeration {
    val ALL = Value("ALL")
    val PATTERN = Value("PATTERN")
    val EXPLICIT = Value("EXPLICIT")
  }

  object PhoneCountry extends Enumeration {
    val US = Value("US")
    val GB = Value("GB")
    val AU = Value("AU")
    val CA = Value("CA")
    val EE = Value("EE")
    val HK = Value("HK")
    val PL = Value("PL")
    val PT = Value("PT")
    val NL = Value("NL")
    val IL = Value("IL")
    val FI = Value("FI")
    val SE = Value("SE")
  }

}

