/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.mailslurp.modelspackageVersion&#x3D;17.2.0


  /**
   * Single expectation to evaluate against each selected entity
   */
case class DeliverabilityExpectation(
  /* Optional label for this expectation */
  name: Option[String] = None,
  /* Minimum number of matching messages required for this expectation to pass */
  minCount: Long,
  /* Optional sender filter. Matching is case-insensitive contains against inbound sender/from values. */
  from: Option[String] = None,
  /* Optional recipient filter. Matching is case-insensitive contains against recipient/to values. */
  to: Option[String] = None,
  /* Optional subject filter for INBOX scope tests. Ignored for PHONE scope tests. */
  subject: Option[String] = None
)


