/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.mailslurp.modelspackageVersion&#x3D;17.2.0


  /**
   * Result of extracting verification codes from message content
   */
case class ExtractCodesResult(
  /* True if at least one code candidate was found */
  found: Boolean,
  /* Best candidate code when found */
  code: Option[String] = None,
  /* Extraction strategy for verification codes. Unsupported strategies may fall back when allowFallback is true. */
  methodUsed: Option[ExtractCodesResultEnums.MethodUsed] = None,
  /* Ranked code candidates */
  candidates: Seq[CodeCandidate],
  /* Warnings or fallback notes explaining extraction behavior for debugging and QA. */
  warnings: Seq[String]
)

object ExtractCodesResultEnums {

  type MethodUsed = MethodUsed.Value
  object MethodUsed extends Enumeration {
    val AUTO = Value("AUTO")
    val PATTERN = Value("PATTERN")
    val LLM = Value("LLM")
    val OCR = Value("OCR")
    val OCRTHENLLM = Value("OCR_THEN_LLM")
  }

}

