/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.mailslurp.modelspackageVersion&#x3D;17.2.0


case class UpdateDevicePreviewFeedbackOptions(
  status: Option[UpdateDevicePreviewFeedbackOptionsEnums.Status] = None,
  rating: Option[Int] = None,
  title: Option[String] = None,
  comment: Option[String] = None,
  internalNote: Option[String] = None,
  appendInternalNote: Option[Boolean] = None,
  sessionId: Option[String] = None,
  liveViewUrl: Option[String] = None,
  metadata: Option[Map[String, String]] = None
)

object UpdateDevicePreviewFeedbackOptionsEnums {

  type Status = Status.Value
  object Status extends Enumeration {
    val OPEN = Value("OPEN")
    val ACKNOWLEDGED = Value("ACKNOWLEDGED")
    val RESOLVED = Value("RESOLVED")
    val DISMISSED = Value("DISMISSED")
  }

}

