/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository 
 *
 * The version of the OpenAPI document: 6.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.mailslurp.modelspackageVersion&#x3D;12.5.0

import java.time.OffsetDateTime
import java.util.UUID

case class WebhookResultEntity(
  createdAt: OffsetDateTime,
  httpMethod: WebhookResultEntityEnums.HttpMethod,
  id: Option[UUID] = None,
  inboxId: UUID,
  messageId: String,
  responseBodyExtract: Option[String] = None,
  responseStatus: Option[Int] = None,
  responseTimeMillis: Long,
  updatedAt: OffsetDateTime,
  userId: UUID,
  webhookEvent: WebhookResultEntityEnums.WebhookEvent,
  webhookId: UUID,
  webhookUrl: String
)

object WebhookResultEntityEnums {

  type HttpMethod = HttpMethod.Value
  type WebhookEvent = WebhookEvent.Value
  object HttpMethod extends Enumeration {
    val GET = Value("GET")
    val HEAD = Value("HEAD")
    val POST = Value("POST")
    val PUT = Value("PUT")
    val PATCH = Value("PATCH")
    val DELETE = Value("DELETE")
    val OPTIONS = Value("OPTIONS")
    val TRACE = Value("TRACE")
  }

  object WebhookEvent extends Enumeration {
    val EMAILRECEIVED = Value("EMAIL_RECEIVED")
    val NEWEMAIL = Value("NEW_EMAIL")
    val NEWCONTACT = Value("NEW_CONTACT")
    val NEWATTACHMENT = Value("NEW_ATTACHMENT")
  }

}

