/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.mailslurp.modelspackageVersion&#x3D;17.3.0

import java.time.OffsetDateTime
import java.util.UUID

  /**
   * Deliverability simulation job status
   */
case class DeliverabilitySimulationJobDto(
  id: UUID,
  testId: UUID,
  scope: DeliverabilitySimulationJobDtoEnums.Scope,
  status: DeliverabilitySimulationJobDtoEnums.Status,
  createdAt: OffsetDateTime,
  updatedAt: OffsetDateTime,
  startedAt: Option[OffsetDateTime] = None,
  completedAt: Option[OffsetDateTime] = None,
  totalTargets: Long,
  totalPlannedSends: Long,
  nextSendIndex: Long,
  sentCount: Long,
  successCount: Long,
  failureCount: Long,
  progressPercent: Double,
  activeTargetLabel: Option[String] = None,
  estimatedRemainingMs: Option[Long] = None,
  configSnapshot: DeliverabilitySimulationJobConfigDto,
  errorSummary: DeliverabilitySimulationJobErrorSummaryDto
)

object DeliverabilitySimulationJobDtoEnums {

  type Scope = Scope.Value
  type Status = Status.Value
  object Scope extends Enumeration {
    val INBOX = Value("INBOX")
    val PHONE = Value("PHONE")
  }

  object Status extends Enumeration {
    val RUNNING = Value("RUNNING")
    val PAUSED = Value("PAUSED")
    val CANCELLED = Value("CANCELLED")
    val COMPLETED = Value("COMPLETED")
    val FAILED = Value("FAILED")
  }

}

