/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.mailslurp.modelspackageVersion&#x3D;17.3.0

import java.time.OffsetDateTime
import java.util.UUID

case class PhoneProvisioningJobDto(
  id: UUID,
  userId: UUID,
  phoneCountry: PhoneProvisioningJobDtoEnums.PhoneCountry,
  phoneVariant: Option[PhoneProvisioningJobDtoEnums.PhoneVariant] = None,
  status: PhoneProvisioningJobDtoEnums.Status,
  requestedCount: Int,
  attemptedCount: Int,
  succeededCount: Int,
  failedCount: Int,
  unavailableCount: Int,
  createdAt: OffsetDateTime,
  updatedAt: OffsetDateTime,
  items: Seq[PhoneProvisioningJobItemDto]
)

object PhoneProvisioningJobDtoEnums {

  type PhoneCountry = PhoneCountry.Value
  type PhoneVariant = PhoneVariant.Value
  type Status = Status.Value
  object PhoneCountry extends Enumeration {
    val US = Value("US")
    val GB = Value("GB")
    val AU = Value("AU")
    val CA = Value("CA")
    val EE = Value("EE")
    val HK = Value("HK")
    val PL = Value("PL")
    val PT = Value("PT")
    val NL = Value("NL")
    val IL = Value("IL")
    val FI = Value("FI")
    val SE = Value("SE")
  }

  object PhoneVariant extends Enumeration {
    val LOCAL = Value("LOCAL")
    val MOBILE = Value("MOBILE")
    val TOLLFREE = Value("TOLL_FREE")
  }

  object Status extends Enumeration {
    val CREATED = Value("CREATED")
    val RUNNING = Value("RUNNING")
    val COMPLETED = Value("COMPLETED")
    val PARTIAL = Value("PARTIAL")
    val FAILED = Value("FAILED")
  }

}

