/**
 * MailSlurp API
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.mailslurp.modelspackageVersion&#x3D;17.3.0

import java.time.OffsetDateTime

case class TenantReputationStatusRowDto(
  accountRegion: TenantReputationStatusRowDtoEnums.AccountRegion,
  tenantName: String,
  tenantArn: Option[String] = None,
  sendingStatus: Option[String] = None,
  reputationStatus: Option[String] = None,
  reputationPolicy: Option[String] = None,
  customerManagedSendingStatus: Option[String] = None,
  awsManagedSendingStatus: Option[String] = None,
  findingCount: Int,
  bounceRate: Option[Double] = None,
  complaintRate: Option[Double] = None,
  sendLastHour: Option[Double] = None,
  metricTimestamp: Option[OffsetDateTime] = None,
  error: Option[String] = None
)

object TenantReputationStatusRowDtoEnums {

  type AccountRegion = AccountRegion.Value
  object AccountRegion extends Enumeration {
    val USWEST2ACCOUNTSTAGING = Value("US_WEST_2_ACCOUNT_STAGING")
    val USEAST1ACCOUNTSTAGING = Value("US_EAST_1_ACCOUNT_STAGING")
    val EUWEST1ACCOUNTSTAGING = Value("EU_WEST_1_ACCOUNT_STAGING")
    val USWEST2ACCOUNTSES1 = Value("US_WEST_2_ACCOUNT_SES_1")
    val EUWEST1ACCOUNTSES1 = Value("EU_WEST_1_ACCOUNT_SES_1")
    val USWEST2ACCOUNTSES2 = Value("US_WEST_2_ACCOUNT_SES_2")
    val EUWEST1ACCOUNTSES2 = Value("EU_WEST_1_ACCOUNT_SES_2")
    val USWEST2ACCOUNTBYTEWISE = Value("US_WEST_2_ACCOUNT_BYTEWISE")
    val EUWEST1ACCOUNTBYTEWISE = Value("EU_WEST_1_ACCOUNT_BYTEWISE")
    val USWEST2 = Value("US_WEST_2")
    val EUWEST1 = Value("EU_WEST_1")
    val USEAST1 = Value("US_EAST_1")
  }

}

